-- À exécuter après create_db.sql, voyages.sql et catalogue_enrichi.sql.
-- 1. Rend le catalogue bilingue (titres et descriptions en anglais, langue des demandes de devis).
-- 2. Élargit le catalogue à 36 destinations (données de démonstration : prix, durées et places sont fictifs).
--    Les voyages existants sont mis à jour (traductions, dates de départ, corrections de pays et de catégories)
--    et les nouvelles destinations sont ajoutées, avec des photos libres de droits (voir CREDITS.md).
SET NAMES utf8mb4;
USE latitudes;

ALTER TABLE voyages
    ADD COLUMN titre_en VARCHAR(255) NULL AFTER titre,
    ADD COLUMN description_en TEXT NULL AFTER description;

-- Langue dans laquelle le visiteur a envoyé sa demande (pour lui répondre dans la même langue)
ALTER TABLE demandes
    ADD COLUMN langue CHAR(2) NOT NULL DEFAULT 'fr' AFTER message;

INSERT INTO voyages
    (id, titre, titre_en, continent, pays, date_depart, categorie, description, description_en,
     prix, duree_jours, places_disponibles, id_utilisateur, image)
VALUES
    (16, 'Plages d’Ibiza', 'Ibiza’s Beaches', 'Europe', 'Espagne', '2027-08-10', 'Plage',
     'Vivez l’alliance parfaite entre farniente, eaux turquoise et ambiance festive dans l’une des destinations balnéaires les plus emblématiques de la Méditerranée.',
     'Enjoy the perfect blend of laziness, turquoise waters and festive spirit on one of the most iconic beach destinations of the Mediterranean.',
     1890, 7, 14, (SELECT id FROM utilisateurs WHERE role = 'admin' ORDER BY id LIMIT 1),
     '["uploads/68616dec9b1b9_espagne1.jpg","uploads/68616dec9b29a_espagne2.jpg","uploads/68616dec9b36c_espagne3.jpg"]'),
    (17, 'Gorges du Verdon', 'Verdon Gorge', 'Europe', 'France', '2027-09-18', 'Nature',
     'Plongez au cœur du plus grand canyon d’Europe, entre falaises calcaires vertigineuses et eaux émeraude. Les Gorges du Verdon offrent un décor spectaculaire pour randonner, pagayer ou simplement admirer la puissance paisible de la nature provençale.',
     'Dive into the heart of Europe’s largest canyon, between dizzying limestone cliffs and emerald waters. The Verdon Gorge is a spectacular setting for hiking, paddling, or simply admiring the peaceful power of Provençal nature.',
     1290, 5, 10, (SELECT id FROM utilisateurs WHERE role = 'admin' ORDER BY id LIMIT 1),
     '["uploads/68616dd780b5c_france2.jpg","uploads/68616dd780cef_france3.jpg"]'),
    (18, 'Safari au Serengeti', 'Serengeti Safari', 'Afrique', 'Tanzanie', '2027-07-05', 'Safari',
     'Partez à la rencontre des plus grands animaux sauvages au cœur d’une nature préservée, là où le rugissement des lions résonne dans l’immensité des plaines dorées.',
     'Meet the planet’s greatest wild animals in the heart of unspoiled nature, where the lions’ roar echoes across the immensity of the golden plains.',
     4590, 8, 8, (SELECT id FROM utilisateurs WHERE role = 'admin' ORDER BY id LIMIT 1),
     '["uploads/68616dc4399e1_tanzanie1.jpg","uploads/68616dc439a3d_tanzanie2.jpg","uploads/68616dc439a87_tanzanie3.jpg","uploads/68616dc439aca_tanzanie4.jpg"]'),
    (19, 'Tokyo by night', 'Tokyo by Night', 'Asie', 'Japon', '2027-10-01', 'Culture',
     'Découvrez une mégalopole où traditions millénaires et technologie de pointe cohabitent dans un tourbillon de lumières, de temples, de ruelles et de grattes-ciel.',
     'Discover a megacity where ancient traditions and cutting-edge technology coexist in a whirl of lights, temples, alleyways and skyscrapers.',
     3490, 9, 12, (SELECT id FROM utilisateurs WHERE role = 'admin' ORDER BY id LIMIT 1),
     '["uploads/68616d9f64f09_japon1.jpg","uploads/68616d9f64f5c_japon2.jpg","uploads/68616d9f64f9e_japon3.jpg"]'),
    (20, 'Désert du Sahara', 'Sahara Desert', 'Afrique', 'Maroc', '2027-12-02', 'Désert',
     'Vivez l’expérience unique d’un bivouac sous les étoiles, d’une balade en dromadaire au milieu des dunes, et d’un silence doré qui semble suspendre le temps.',
     'Experience a unique bivouac under the stars, a camel ride among the dunes, and a golden silence that seems to suspend time.',
     1990, 6, 16, (SELECT id FROM utilisateurs WHERE role = 'admin' ORDER BY id LIMIT 1),
     '["uploads/68616d876a0a9_maroc1.jpg","uploads/68616d876a0f5_maroc2.jpg","uploads/68616d876a139_maroc3.jpg"]'),
    (21, 'Îles Phi Phi', 'Phi Phi Islands', 'Asie', 'Thaïlande', '2027-11-20', 'Île tropicale',
     'Entre falaises de calcaire plongeant dans une mer cristalline et plages secrètes bordées de cocotiers, ces îles sont une ode à l’évasion et à la beauté naturelle.',
     'Between limestone cliffs plunging into crystal-clear seas and secret beaches lined with coconut palms, these islands are an ode to escape and natural beauty.',
     2790, 10, 6, (SELECT id FROM utilisateurs WHERE role = 'admin' ORDER BY id LIMIT 1),
     '["uploads/68616d4947476_thailande1.jpg","uploads/68616d49474d8_thailande2.jpg","uploads/68616d494752c_thailande3.jpg"]'),
    (22, 'Rizières de Bali', 'Bali’s Rice Terraces', 'Asie', 'Indonésie', '2027-09-01', 'Nature',
     'Un paysage vivant d’harmonie verte sculptée par l’homme : les rizières balinaises forment une mosaïque paisible, reflet d’une culture profondément spirituelle.',
     'A living landscape of green harmony sculpted by people: Bali’s rice terraces form a peaceful mosaic, reflecting a deeply spiritual culture.',
     2490, 10, 12, (SELECT id FROM utilisateurs WHERE role = 'admin' ORDER BY id LIMIT 1),
     '["uploads/68616cf9e38d3_bali1.jpg","uploads/68616cf9e3915_bali2.jpg","uploads/68616cf9e395a_bali3.jpg"]'),
    (23, 'Zermatt et le Cervin', 'Zermatt and the Matterhorn', 'Europe', 'Suisse', '2027-12-20', 'Montagne',
     'Au pied du légendaire Cervin, Zermatt vous accueille dans un paysage de carte postale où chalets en bois, pistes enneigées et ciel cristallin composent un décor alpin inoubliable. Skiez, flânez, ou admirez la montagne la plus photogénique d’Europe dans toute sa majesté hivernale.',
     'At the foot of the legendary Matterhorn, Zermatt welcomes you to a postcard landscape where wooden chalets, snowy slopes and crystal-clear skies make an unforgettable alpine setting. Ski, stroll, or admire Europe’s most photogenic mountain in all its winter majesty.',
     2890, 7, 4, (SELECT id FROM utilisateurs WHERE role = 'admin' ORDER BY id LIMIT 1),
     '["uploads/68616ce0608ba_suisse1.jpg","uploads/68616ce060933_suisse2.jpg","uploads/68616ce060990_suisse3.jpg"]'),
    (24, 'Road trip en Californie', 'California Road Trip', 'Amérique', 'États-Unis', '2027-08-22', 'Nature',
     'Explorez la route côtière la plus célèbre du monde, entre plages de surf, séquoias géants, déserts californiens et villes mythiques comme San Francisco et L.A.',
     'Explore the world’s most famous coastal road, between surf beaches, giant redwoods, Californian deserts and legendary cities like San Francisco and L.A.',
     3190, 12, 9, (SELECT id FROM utilisateurs WHERE role = 'admin' ORDER BY id LIMIT 1),
     '["uploads/68616cce791d0_États-Unis1.avif","uploads/68616cce79217_États-Unis2.jpg","uploads/68616cce79257_États-Unis3.jpg"]'),
    (25, 'Chutes d’Iguazú', 'Iguazú Falls', 'Amérique', 'Brésil', '2027-11-10', 'Nature',
     'Une force brute de la nature où 275 cascades se déversent dans une jungle luxuriante : un choc visuel et sonore qui émerveille chaque voyageur.',
     'A raw force of nature where 275 waterfalls pour into a lush jungle: a visual and sonic shock that amazes every traveller.',
     2990, 8, 10, (SELECT id FROM utilisateurs WHERE role = 'admin' ORDER BY id LIMIT 1),
     '["uploads/68616cbcd372e_Brésil1.jpg","uploads/68616cbcd377c_Brésil2.jpg","uploads/68616cbcd37bf_Brésil3.jpg"]'),
    (26, 'Coucher de soleil à Santorin', 'Sunset in Santorini', 'Europe', 'Grèce', '2027-09-10', 'Île tropicale',
     'Perchée au sommet de falaises volcaniques, l’île de Santorin vous offre des couchers de soleil légendaires sur la mer Égée, entre dômes bleus, maisons blanches éclatantes et ruelles fleuries. Une expérience romantique et lumineuse, suspendue entre ciel et mer.',
     'Perched on top of volcanic cliffs, the island of Santorini offers legendary sunsets over the Aegean Sea, among blue domes, dazzling white houses and flowered alleys. A romantic, luminous experience suspended between sky and sea.',
     2390, 7, 0, (SELECT id FROM utilisateurs WHERE role = 'admin' ORDER BY id LIMIT 1),
     '["uploads/68616ca02ca7b_Grèce1.jpg","uploads/68616ca02cb4d_Grèce2.jpg","uploads/68616ca02cb97_Grèce3.jpg"]'),
    (27, 'Machu Picchu', 'Machu Picchu', 'Amérique', 'Pérou', '2027-09-30', 'Montagne',
     'Ancienne cité inca perchée dans les nuages, le Machu Picchu vous invite à un pèlerinage entre mystère, nature et splendeur historique.',
     'An ancient Inca city perched in the clouds, Machu Picchu invites you on a pilgrimage of mystery, nature and historical splendour.',
     3290, 9, 8, (SELECT id FROM utilisateurs WHERE role = 'admin' ORDER BY id LIMIT 1),
     '["uploads/68616c9020701_Argentine1.jpg","uploads/68616c9020767_Argentine2.jpg","uploads/68616c90207c1_Argentine3.jpg"]'),
    (28, 'Réserve de Kruger', 'Kruger National Park', 'Afrique', 'Afrique du Sud', '2027-07-15', 'Safari',
     'Le royaume de la vie sauvage africaine : partez en 4x4 sur les pistes de cette immense réserve à la recherche d’éléphants, lions, rhinocéros et bien plus.',
     'The kingdom of African wildlife: set off by 4x4 along the tracks of this immense reserve in search of elephants, lions, rhinos and much more.',
     3990, 8, 6, (SELECT id FROM utilisateurs WHERE role = 'admin' ORDER BY id LIMIT 1),
     '["uploads/68616c8224d02_Afrique du Sud1.jpg","uploads/68616c8224d81_Afrique du Sud2.jpg","uploads/68616c8224df0_Afrique du Sud3.jpg"]'),
    (29, 'Dunes de Dubaï', 'Dubai Dunes', 'Asie', 'Émirats arabes unis', '2027-12-05', 'Désert',
     'Embarquez pour un safari dans les dunes, admirez le coucher du soleil orangé, puis savourez un dîner oriental dans un camp bédouin au clair de lune.',
     'Set off on a dune safari, admire the orange sunset, then enjoy an oriental dinner in a Bedouin camp under the moonlight.',
     2590, 6, 15, (SELECT id FROM utilisateurs WHERE role = 'admin' ORDER BY id LIMIT 1),
     '["uploads/68616c567784e_Émirats arabes unis1.jpg","uploads/68616c5677909_Émirats arabes unis2.jpg","uploads/68616c56779a0_Émirats arabes unis3.jpg"]'),
    (30, 'Grande Barrière de Corail', 'Great Barrier Reef', 'Océanie', 'Australie', '2027-10-12', 'Île tropicale',
     'Plongez dans le plus vaste récif corallien au monde : un monde sous-marin coloré, vibrant de vie, à préserver absolument pour les générations futures.',
     'Dive into the largest coral reef in the world: a colourful, vibrant underwater world that must be preserved for future generations.',
     4290, 10, 5, (SELECT id FROM utilisateurs WHERE role = 'admin' ORDER BY id LIMIT 1),
     '["uploads/grande-barriere-1.jpg","uploads/grande-barriere-2.jpg","uploads/grande-barriere-3.jpg"]'),
    (52, 'Aventure au cœur des Alpes du Sud, Queenstown', 'Adventure in the Southern Alps, Queenstown', 'Océanie', 'Nouvelle-Zélande', '2027-12-10', 'Montagne',
     'Entourée de sommets enneigés et bordée par le lac Wakatipu aux eaux cristallines, Queenstown est le paradis des amateurs de nature et de sensations fortes. C’est ici que le saut à l’élastique est né, et l’on peut y pratiquer ski, VTT, kayak ou randonnées panoramiques. L’ambiance y est chaleureuse, entre cafés branchés, marchés locaux et vues spectaculaires à couper le souffle.',
     'Surrounded by snow-capped peaks and bordered by the crystal-clear waters of Lake Wakatipu, Queenstown is a paradise for nature lovers and thrill-seekers. Bungee jumping was born here, and you can also ski, mountain bike, kayak or hike panoramic trails. The atmosphere is warm, with trendy cafés, local markets and breathtaking views.',
     4190, 10, 7, (SELECT id FROM utilisateurs WHERE role = 'admin' ORDER BY id LIMIT 1),
     '["uploads/queenstown-1.jpg","uploads/queenstown-2.jpg","uploads/queenstown-3.jpg"]'),
    (53, 'Sur les traces de la Renaissance, Florence', 'In the Footsteps of the Renaissance, Florence', 'Europe', 'Italie', '2027-09-20', 'Culture',
     'Berceau de la Renaissance, Florence regorge de trésors artistiques et architecturaux. La cathédrale Santa Maria del Fiore domine une ville où chaque rue raconte une histoire. Musées, palais, galeries d’art et marchés en plein air se côtoient dans une atmosphère à la fois élégante et vivante. Un incontournable pour les passionnés d’histoire, de gastronomie et de culture italienne.',
     'Cradle of the Renaissance, Florence is full of artistic and architectural treasures. The Santa Maria del Fiore cathedral dominates a city where every street tells a story. Museums, palaces, art galleries and open-air markets sit side by side in an atmosphere that is both elegant and lively. A must for lovers of history, gastronomy and Italian culture.',
     2190, 6, 12, (SELECT id FROM utilisateurs WHERE role = 'admin' ORDER BY id LIMIT 1),
     '["uploads/florence-1.jpg","uploads/florence-2.jpg","uploads/florence-3.jpg"]'),
    (54, 'Mystères et merveilles des pyramides, Le Caire', 'Mysteries and Wonders of the Pyramids, Cairo', 'Afrique', 'Égypte', '2027-11-12', 'Culture',
     'Ville millénaire posée sur les rives du Nil, Le Caire abrite l’un des trésors les plus fascinants de l’humanité : les pyramides de Gizeh. Face au désert, les imposants monuments de Khéops, Khéphren et Mykérinos racontent les récits de l’Égypte antique. Non loin de là, le Sphinx veille en silence depuis des millénaires. Entre musées, souks animés et balades sur le Nil, Le Caire est une immersion vivante dans l’histoire et la grandeur des civilisations anciennes.',
     'A thousand-year-old city on the banks of the Nile, Cairo is home to one of humanity’s most fascinating treasures: the Giza pyramids. Facing the desert, the imposing monuments of Khufu, Khafre and Menkaure tell the stories of ancient Egypt. Not far away, the Sphinx has been keeping silent watch for millennia. Between museums, bustling souks and walks along the Nile, Cairo is a living immersion in the history and greatness of ancient civilisations.',
     2690, 8, 10, (SELECT id FROM utilisateurs WHERE role = 'admin' ORDER BY id LIMIT 1),
     '["uploads/le-caire-1.jpg","uploads/le-caire-2.jpg","uploads/le-caire-3.jpg"]'),
    (60, 'Aurores boréales en Islande', 'Northern Lights in Iceland', 'Europe', 'Islande', '2027-02-14', 'Nature',
     'Chassez les aurores boréales au-dessus de volcans endormis, de glaciers turquoise et de cascades géantes. Entre sources chaudes, plages de sable noir et lagons de glace, l’Islande offre un spectacle naturel hors du commun.',
     'Chase the northern lights above sleeping volcanoes, turquoise glaciers and giant waterfalls. Between hot springs, black-sand beaches and glacier lagoons, Iceland offers an extraordinary natural spectacle.',
     3390, 8, 10, (SELECT id FROM utilisateurs WHERE role = 'admin' ORDER BY id LIMIT 1),
     '["uploads/islande-1.jpg","uploads/islande-2.jpg","uploads/islande-3.jpg"]'),
    (61, 'Fjords de Norvège', 'Norwegian Fjords', 'Europe', 'Norvège', '2027-06-19', 'Nature',
     'Naviguez au pied de falaises vertigineuses et de cascades qui plongent dans des fjords d’un bleu profond. Randonnées, villages de pêcheurs colorés et soleil de minuit composent un séjour au cœur de paysages grandioses.',
     'Sail beneath dizzying cliffs and waterfalls plunging into deep blue fjords. Hikes, colourful fishing villages and the midnight sun make for a stay in the heart of grandiose landscapes.',
     3690, 8, 12, (SELECT id FROM utilisateurs WHERE role = 'admin' ORDER BY id LIMIT 1),
     '["uploads/norvege-1.jpg","uploads/norvege-2.jpg","uploads/norvege-3.jpg"]'),
    (62, 'Algarve, la côte dorée', 'The Algarve, the Golden Coast', 'Europe', 'Portugal', '2027-07-10', 'Plage',
     'Falaises dorées, grottes marines et criques secrètes : l’Algarve offre certaines des plus belles plages d’Europe. Profitez du soleil, de la cuisine de la mer et de villages blancs aux ruelles paisibles.',
     'Golden cliffs, sea caves and secret coves: the Algarve boasts some of Europe’s most beautiful beaches. Enjoy the sun, fresh seafood and whitewashed villages with peaceful lanes.',
     1790, 7, 16, (SELECT id FROM utilisateurs WHERE role = 'admin' ORDER BY id LIMIT 1),
     '["uploads/algarve-1.jpg","uploads/algarve-2.jpg","uploads/algarve-3.jpg"]'),
    (63, 'Dubrovnik et la côte dalmate', 'Dubrovnik and the Dalmatian Coast', 'Europe', 'Croatie', '2027-09-05', 'Culture',
     'Remparts de pierre blanche, îles adriatiques et palais antiques : la côte dalmate mêle histoire et mer d’un bleu limpide. Flânez dans la vieille ville de Dubrovnik et explorez Split et ses ruelles romaines.',
     'White stone ramparts, Adriatic islands and ancient palaces: the Dalmatian coast blends history with crystal-clear blue sea. Stroll through Dubrovnik’s old town and explore Split and its Roman lanes.',
     2190, 8, 14, (SELECT id FROM utilisateurs WHERE role = 'admin' ORDER BY id LIMIT 1),
     '["uploads/dubrovnik-1.jpg","uploads/dubrovnik-2.jpg","uploads/dubrovnik-3.jpg"]'),
    (64, 'Rocheuses canadiennes, Banff', 'Canadian Rockies, Banff', 'Amérique', 'Canada', '2027-08-14', 'Montagne',
     'Lacs turquoise, sommets enneigés et forêts à perte de vue : le parc national de Banff est un sanctuaire de nature sauvage. Randonnée, canot et rencontres avec la faune au cœur des Rocheuses.',
     'Turquoise lakes, snow-capped peaks and endless forests: Banff National Park is a sanctuary of wild nature. Hiking, canoeing and wildlife encounters in the heart of the Rockies.',
     3190, 9, 10, (SELECT id FROM utilisateurs WHERE role = 'admin' ORDER BY id LIMIT 1),
     '["uploads/banff-1.jpg","uploads/banff-2.jpg","uploads/banff-3.jpg"]'),
    (65, 'Tulum et les cénotes du Yucatán', 'Tulum and the Yucatán Cenotes', 'Amérique', 'Mexique', '2027-03-12', 'Plage',
     'Ruines mayas au bord de la mer des Caraïbes, cénotes aux eaux cristallines et plages de sable blanc. Un séjour qui réunit histoire, baignade en pleine jungle et détente.',
     'Mayan ruins beside the Caribbean Sea, crystal-clear cenotes and white-sand beaches. A stay that combines history, jungle swimming and relaxation.',
     1990, 7, 14, (SELECT id FROM utilisateurs WHERE role = 'admin' ORDER BY id LIMIT 1),
     '["uploads/tulum-1.jpg","uploads/tulum-2.jpg","uploads/tulum-3.jpg"]'),
    (66, 'Patagonie, glacier Perito Moreno', 'Patagonia, Perito Moreno Glacier', 'Amérique', 'Argentine', '2027-02-20', 'Nature',
     'Marchez face au glacier Perito Moreno, muraille de glace bleutée, puis découvrez les sommets acérés du Fitz Roy. La Patagonie argentine, ce sont des horizons infinis et des paysages spectaculaires.',
     'Stand before the Perito Moreno Glacier, a bluish wall of ice, then discover the jagged peaks of Mount Fitz Roy. Argentine Patagonia means endless horizons and spectacular landscapes.',
     3890, 9, 8, (SELECT id FROM utilisateurs WHERE role = 'admin' ORDER BY id LIMIT 1),
     '["uploads/patagonie-1.jpg","uploads/patagonie-2.jpg","uploads/patagonie-3.jpg"]'),
    (67, 'Costa Rica sauvage', 'Wild Costa Rica', 'Amérique', 'Costa Rica', '2027-01-23', 'Nature',
     'Volcans, forêts nuageuses, plages du Pacifique et faune exubérante : le Costa Rica est un paradis pour les amoureux de la nature. Observez singes, paresseux et oiseaux colorés au fil des sentiers.',
     'Volcanoes, cloud forests, Pacific beaches and exuberant wildlife: Costa Rica is a paradise for nature lovers. Spot monkeys, sloths and colourful birds along the trails.',
     2790, 9, 12, (SELECT id FROM utilisateurs WHERE role = 'admin' ORDER BY id LIMIT 1),
     '["uploads/costa-rica-1.jpg","uploads/costa-rica-2.jpg","uploads/costa-rica-3.jpg"]'),
    (68, 'Baie d’Ha Long et Vietnam authentique', 'Ha Long Bay and Authentic Vietnam', 'Asie', 'Viêt Nam', '2027-11-06', 'Nature',
     'Croisière entre des milliers d’îlots calcaires dans la baie d’Ha Long, puis promenade dans la vieille ville de Hội An et ses lanternes. Un voyage entre paysages féeriques et saveurs locales.',
     'Cruise among thousands of limestone islets in Ha Long Bay, then wander through Hội An’s old town and its lanterns. A journey of fairytale landscapes and local flavours.',
     2390, 9, 15, (SELECT id FROM utilisateurs WHERE role = 'admin' ORDER BY id LIMIT 1),
     '["uploads/vietnam-1.jpg","uploads/vietnam-2.jpg","uploads/vietnam-3.jpg"]'),
    (69, 'Himalaya, trek de l’Annapurna', 'Himalayas, Annapurna Trek', 'Asie', 'Népal', '2027-04-10', 'Montagne',
     'Un trek mythique au pied des géants de l’Himalaya, entre villages de montagne, rhododendrons en fleurs et levers de soleil sur l’Annapurna. Accessible aux marcheurs réguliers, accompagné de guides locaux.',
     'A legendary trek at the foot of the Himalayan giants, through mountain villages, blooming rhododendrons and sunrises over Annapurna. Suitable for regular hikers, with local guides.',
     3290, 12, 8, (SELECT id FROM utilisateurs WHERE role = 'admin' ORDER BY id LIMIT 1),
     '["uploads/nepal-1.jpg","uploads/nepal-2.jpg","uploads/nepal-3.jpg"]'),
    (70, 'Rajasthan et Taj Mahal', 'Rajasthan and the Taj Mahal', 'Asie', 'Inde', '2027-10-16', 'Culture',
     'Du Taj Mahal aux palais de Jaipur, plongez dans la richesse du nord de l’Inde : forts majestueux, bazars colorés et traditions vivantes. Un voyage haut en couleurs et en saveurs.',
     'From the Taj Mahal to the palaces of Jaipur, dive into the richness of northern India: majestic forts, colourful bazaars and living traditions. A journey full of colour and flavour.',
     2590, 10, 14, (SELECT id FROM utilisateurs WHERE role = 'admin' ORDER BY id LIMIT 1),
     '["uploads/rajasthan-1.jpg","uploads/rajasthan-2.jpg","uploads/rajasthan-3.jpg"]'),
    (71, 'Petra et le désert du Wadi Rum', 'Petra and the Wadi Rum Desert', 'Asie', 'Jordanie', '2027-03-27', 'Désert',
     'Découvrez Petra, la cité rose taillée dans la roche, puis passez une nuit sous les étoiles dans le désert du Wadi Rum. Histoire nabatéenne et paysages lunaires réunis en une semaine.',
     'Discover Petra, the rose-red city carved into the rock, then spend a night under the stars in the Wadi Rum desert. Nabataean history and lunar landscapes combined in one week.',
     2890, 7, 12, (SELECT id FROM utilisateurs WHERE role = 'admin' ORDER BY id LIMIT 1),
     '["uploads/jordanie-1.jpg","uploads/jordanie-2.jpg","uploads/jordanie-3.jpg"]'),
    (72, 'Maldives, l’évasion absolue', 'Maldives, the Ultimate Escape', 'Asie', 'Maldives', '2027-01-30', 'Île tropicale',
     'Atolls de sable blanc, lagons turquoise et villas sur pilotis : les Maldives sont l’adresse rêvée pour se ressourcer. Plongée, snorkeling et coucher de soleil les pieds dans l’eau.',
     'White-sand atolls, turquoise lagoons and overwater villas: the Maldives is the dream address for recharging. Diving, snorkelling and sunsets with your feet in the water.',
     4990, 7, 10, (SELECT id FROM utilisateurs WHERE role = 'admin' ORDER BY id LIMIT 1),
     '["uploads/maldives-1.jpg","uploads/maldives-2.jpg","uploads/maldives-3.jpg"]'),
    (73, 'Safari au Masai Mara', 'Masai Mara Safari', 'Afrique', 'Kenya', '2027-08-07', 'Safari',
     'Assistez à l’un des plus grands spectacles animaliers du monde : la grande migration des gnous. Lions, girafes et éléphants vous attendent sur les plaines du Masai Mara.',
     'Witness one of the world’s greatest wildlife spectacles: the great wildebeest migration. Lions, giraffes and elephants await you on the plains of the Masai Mara.',
     4290, 8, 8, (SELECT id FROM utilisateurs WHERE role = 'admin' ORDER BY id LIMIT 1),
     '["uploads/kenya-1.jpg","uploads/kenya-2.jpg","uploads/kenya-3.jpg"]'),
    (74, 'Dunes de Sossusvlei', 'Sossusvlei Dunes', 'Afrique', 'Namibie', '2027-05-15', 'Désert',
     'Gravissez les plus hautes dunes du monde au lever du soleil et découvrez Deadvlei, ses arbres fossilisés et son sol blanc craquelé. La Namibie, c’est un désert de contrastes et de silence.',
     'Climb some of the world’s highest dunes at sunrise and discover Deadvlei, with its fossilised trees and cracked white clay. Namibia is a desert of contrasts and silence.',
     3990, 9, 10, (SELECT id FROM utilisateurs WHERE role = 'admin' ORDER BY id LIMIT 1),
     '["uploads/namibie-1.jpg","uploads/namibie-2.jpg","uploads/namibie-3.jpg"]'),
    (75, 'Bora-Bora et les îles de la Société', 'Bora Bora and the Society Islands', 'Océanie', 'Polynésie française', '2027-06-05', 'Île tropicale',
     'Lagons aux mille nuances de bleu, montagnes verdoyantes et bungalows sur l’eau : Bora-Bora et Moorea incarnent le paradis polynésien. Plongée avec les raies et détente absolue.',
     'Lagoons in a thousand shades of blue, green mountains and overwater bungalows: Bora Bora and Moorea embody Polynesian paradise. Diving with rays and total relaxation.',
     6490, 10, 8, (SELECT id FROM utilisateurs WHERE role = 'admin' ORDER BY id LIMIT 1),
     '["uploads/polynesie-1.jpg","uploads/polynesie-2.jpg","uploads/polynesie-3.jpg"]'),
    (76, 'Kyoto, temples et traditions', 'Kyoto, Temples and Traditions', 'Asie', 'Japon', '2027-11-13', 'Culture',
     'Sous les milliers de torii du Fushimi Inari, dans les jardins du Kinkaku-ji ou la forêt de bambous d’Arashiyama, Kyoto vous plonge dans le Japon des traditions. Cérémonie du thé, quartiers de geishas et cuisine kaiseki.',
     'Beneath the thousands of torii gates of Fushimi Inari, in the gardens of Kinkaku-ji or the Arashiyama bamboo grove, Kyoto immerses you in traditional Japan. Tea ceremony, geisha districts and kaiseki cuisine.',
     3690, 9, 12, (SELECT id FROM utilisateurs WHERE role = 'admin' ORDER BY id LIMIT 1),
     '["uploads/kyoto-1.jpg","uploads/kyoto-2.jpg","uploads/kyoto-3.jpg"]'),
    (77, 'Cappadoce en montgolfière', 'Cappadocia by Hot-Air Balloon', 'Asie', 'Turquie', '2027-05-01', 'Culture',
     'Survolez au lever du soleil les cheminées de fées et les vallées de tuf de Cappadoce. Villages troglodytes, hôtels creusés dans la roche et cuisine anatolienne complètent cette expérience unique.',
     'Fly over Cappadocia’s fairy chimneys and tuff valleys at sunrise. Cave villages, hotels carved into the rock and Anatolian cuisine complete this unique experience.',
     2190, 7, 14, (SELECT id FROM utilisateurs WHERE role = 'admin' ORDER BY id LIMIT 1),
     '["uploads/cappadoce-1.jpg","uploads/cappadoce-2.jpg","uploads/cappadoce-3.jpg"]')
ON DUPLICATE KEY UPDATE
    titre = VALUES(titre), titre_en = VALUES(titre_en), continent = VALUES(continent), pays = VALUES(pays),
    date_depart = VALUES(date_depart), categorie = VALUES(categorie), description = VALUES(description),
    description_en = VALUES(description_en), prix = VALUES(prix), duree_jours = VALUES(duree_jours),
    places_disponibles = VALUES(places_disponibles), image = VALUES(image);
